-- Hackerrank Challenge Binary Tree Nodes

SELECT N, 
CASE WHEN B_INNER.P IS NULL THEN 'LEAF' ELSE 'INNER' END NODETYPE 
FROM 
(SELECT DISTINCT BN.N,BP.P FROM 
(SELECT N FROM BST WHERE P IS NOT NULL) BN
LEFT JOIN (SELECT P FROM BST WHERE P IS NOT NULL) BP 
ON BN.N = BP.P) B_INNER
UNION ALL (
SELECT N, 'ROOT' NODETYPE 
FROM BST WHERE P IS NULL);
