-- Hackerrank Challenge Binary Tree Nodes

SELECT N, 
CASE WHEN B_INNER.P IS NULL THEN 'Leaf' ELSE 'Inner' END NODETYPE 
FROM 
(SELECT DISTINCT BN.N, BP.P FROM 
(SELECT N FROM BST WHERE P IS NOT NULL) BN
LEFT JOIN (SELECT P FROM BST WHERE P IS NOT NULL) BP 
ON BN.N = BP.P) B_INNER
UNION ALL (
SELECT N, 'Root' NODETYPE 
FROM BST WHERE P IS NULL)
ORDER BY 1 ASC;
